name: Inception

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: mariadb.Dockerfile
    env_file:
      - .env
    restart: on-failure
    secrets:
      - mariadb_root_password
      - mariadb_password
    volumes:
      - ~/data/mariadb:/var/lib/mysql:rw

  nginx:
    build:
      context: requirements/nginx
      dockerfile: nginx.Dockerfile
    depends_on:
      - wordpress-php
    env_file:
      - .env
    extra_hosts:
      - cteoh.42.fr=127.0.0.1
      - www.cteoh.42.fr=127.0.0.1
    ports:
      - 127.0.0.1:443:443
      - 127.0.0.1:80:80
    restart: on-failure
    secrets:
      - server.rsa.crt
      - server.rsa.key
    volumes_from:
      - wordpress-php:ro
      
  wordpress-php:
    build:
      context: requirements/wordpress
      dockerfile: wordpress-php.Dockerfile
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure
    secrets:
      - mariadb_password
    volumes:
      - ~/data/wordpress:/var/www/html:rw
      - realtime:/usr/share/php83/fpm:ro

secrets:
  server.rsa.crt:
    file: ../secrets/server.rsa.crt
  server.rsa.key:
    file: ../secrets/server.rsa.key
  mariadb_root_password:
    file: ../secrets/mariadb_root_password
  mariadb_password:
    file: ../secrets/mariadb_password

volumes:
  realtime: