name: Inception

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: mariadb.Dockerfile
    env_file:
      - .env
    networks:
      - infra
    restart: on-failure
    secrets:
      - mariadb_root_password
      - mariadb_password
    volumes:
      - ~/data/mariadb:/var/lib/mysql:rw

  nginx:
    build:
      context: requirements/nginx/
      dockerfile: nginx.Dockerfile
    depends_on:
      - wordpress-php
    env_file:
      - .env
    networks:
      - infra
    ports:
      - 127.0.0.1:32768:80
      - 127.0.0.1:32769:443
    restart: on-failure
    secrets:
      - server.rsa.crt
      - server.rsa.key
    volumes_from:
      - wordpress-php:ro

  redis:
    build:
      context: requirements/bonus/redis/
      dockerfile: redis.Dockerfile
    networks:
      - infra
    restart: on-failure

  wordpress-php:
    build:
      context: requirements/wordpress/
      dockerfile: wordpress-php.Dockerfile
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    networks:
      - infra
    restart: on-failure
    secrets:
      - mariadb_password
    volumes:
      - ~/data/wordpress:/var/www/html:rw
      - realtime:/usr/share/php83/fpm:ro

networks:
  infra:
    driver: bridge

secrets:
  server.rsa.crt:
    file: ../secrets/server.rsa.crt
  server.rsa.key:
    file: ../secrets/server.rsa.key
  mariadb_root_password:
    file: ../secrets/mariadb_root_password
  mariadb_password:
    file: ../secrets/mariadb_password

volumes:
  realtime: