name: Inception

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile.nginx
    extra_hosts:
      - cteoh.42.fr=127.0.0.1
      - www.cteoh.42.fr=127.0.0.1
    ports:
      - 127.0.0.1:443:443
      - 127.0.0.1:80:80
    secrets:
      - server.rsa.crt
      - server.rsa.key
    depends_on:
      - wordpress-php
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ~/data/wordpress:/var/www/html:ro
      
  wordpress-php:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile.wordpress-php
    volumes:
      - ~/data/wordpress:/var/www/html:ro

secrets:
  server.rsa.crt:
    file: ../secrets/server.rsa.crt
  server.rsa.key:
    file: ../secrets/server.rsa.key